### ISSUE TITLE
CI doesn't checkout spdk-csi sources correctly

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk-csi#38]
See: https://review.spdk.io/gerrit/c/spdk/spdk-csi/+/18520
https://ci.spdk.io/public_build/spdk-csi-per-patch_144.html

CI fails to check out and test the change because of:
```
08:31:37  Setting http proxy: proxy-dmz.intel.com:911
08:31:37   > git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk refs/changes/20/18520/2 +refs/heads/master:refs/remotes/origin/master # timeout=10
08:31:38  ERROR: Error fetching remote repo 'origin'
08:31:38  hudson.plugins.git.GitException: Failed to fetch from https://review.spdk.io/gerrit/a/spdk/spdk
08:31:38  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
08:31:38  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1241)
08:31:38  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
08:31:38  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
08:31:38  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
08:31:38  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
08:31:38  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
08:31:38  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
08:31:38  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
08:31:38  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
08:31:38  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
08:31:38  	at java.base/java.lang.Thread.run(Thread.java:840)
08:31:38  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://review.spdk.io/gerrit/a/spdk/spdk refs/changes/20/18520/2 +refs/heads/master:refs/remotes/origin/master" returned status code 128:
08:31:38  stdout: 
08:31:38  stderr: fatal: couldn't find remote ref refs/changes/20/18520/2
```

Seems there is something wrong with Jenkins build parameters and it tries to checkout spdk/spdk instead of spdk/spdk-csi

**Comment by kgodzwox** [comment]
Fixed on the CI side. Closing
